// <auto-generated />
namespace PersonalEstore.cs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class chng_in_color_of_Clothes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chng_in_color_of_Clothes));
        
        string IMigrationMetadata.Id
        {
            get { return "202006021513455_chng_in_color_of_Clothes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
