// <auto-generated />
namespace PersonalEstore.cs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class categoryadded2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(categoryadded2));
        
        string IMigrationMetadata.Id
        {
            get { return "202005311601238_categoryadded2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
